dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libeigen3-dev
     - cppcheck
script:
 - cd ros_lidar_obstacle_detection/lib/lidar_obstacle_detection
 - ./.build.sh
 - ./.run_tests.sh
 - cd ../../..
 - ./.cppcheck-all.sh

