dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libeigen3-dev

script:
 - cmake ./lidar_obstacle_detection
 - cmake --build ./lidar_obstacle_detection -- -j2

